const DEFAULT_ERROR = 500;
const REQUEST_NOT_FOUND = 404;
const INVALID_REQUEST = 400;
const UNAUTHORIZED = 401;
const DUPLICATE = 11000;

module.exports = { DEFAULT_ERROR, REQUEST_NOT_FOUND, INVALID_REQUEST, DUPLICATE, UNAUTHORIZED };
